# Generated by Django 2.0.2 on 2018-03-20 15:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.IntegerField(default=3, validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('ADMIN', 'A'), ('STUDENT', 'S'), ('FACULTY', 'F'), ('RESEARCHER', 'R')], max_length=1),
        ),
    ]
