# Generated by Django 2.0.2 on 2018-03-21 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_system', '0002_auto_20180320_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='seat_capacity',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('S', 'S'), ('F', 'F'), ('R', 'R')], max_length=1),
        ),
    ]
