# Generated by Django 2.0.2 on 2018-03-21 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_system', '0003_auto_20180321_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='faculty_type',
            field=models.CharField(choices=[('P', 'P'), ('F', 'F')], max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_type',
            field=models.CharField(choices=[('F', 'F'), ('P', 'P')], max_length=1),
        ),
    ]
