# Generated by Django 2.0.2 on 2018-03-21 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_system', '0004_auto_20180321_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingdays',
            name='day_1',
            field=models.CharField(choices=[('MONDAY', 'MONDAY'), ('TUESDAY', 'TUESDAY'), ('WEDNESDAY', 'WEDNDESDAY'), ('THURSDAY', 'THURSDAY'), ('FRIDAY', 'FRIDAY'), ('SATURDAY', 'SATURDAY'), ('SUNDAY', 'SUNDAY')], max_length=10),
        ),
        migrations.AlterField(
            model_name='meetingdays',
            name='day_2',
            field=models.CharField(choices=[('MONDAY', 'MONDAY'), ('TUESDAY', 'TUESDAY'), ('WEDNESDAY', 'WEDNDESDAY'), ('THURSDAY', 'THURSDAY'), ('FRIDAY', 'FRIDAY'), ('SATURDAY', 'SATURDAY'), ('SUNDAY', 'SUNDAY')], max_length=10),
        ),
    ]
