# Generated by Django 2.0.2 on 2018-03-22 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_system', '0006_auto_20180321_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hold',
            name='name',
            field=models.CharField(choices=[('ACADEMIC', 'ACADEMIC'), ('DISCIPLINARY', 'DISCIPLINARY'), ('FINANCIAL', 'FINANCIAL'), ('MEDICAL', 'MEDICAL')], max_length=100),
        ),
    ]
