# Generated by Django 2.0.2 on 2018-03-29 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_system', '0009_auto_20180328_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenthistory',
            name='status',
            field=models.CharField(choices=[('FRESHMAN', 'FRESHMAN'), ('SOPHOMORE', 'SOPHOMORE'), ('JUNIOR', 'JUNIOR'), ('SENIOR', 'SENIOR'), ('GRADUATE', 'GRADUATE'), ('GRADUATE_STUDENT', 'GRADUATE_STUDENT')], max_length=35),
        ),
    ]
