# Generated by Django 2.0.2 on 2018-04-04 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration_system', '0010_auto_20180328_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='building_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration_system.Building'),
        ),
    ]
