# Generated by Django 2.0.2 on 2018-04-08 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_system', '0011_auto_20180403_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetings',
            name='meeting_date',
            field=models.DateTimeField(null=True, verbose_name='meeting date'),
        ),
    ]
