# Generated by Django 2.0.2 on 2018-04-09 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_system', '0013_auto_20180408_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetings',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
