# Generated by Django 2.0.2 on 2018-04-15 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration_system', '0014_meetings_submitted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetings',
            name='submitted',
        ),
    ]
